### ISSUE TITLE
Select & Down didn`t work changed 

### ISSUE THREAD

**Issue by Meins321** [Erriez/ErriezLCDKeypadShield#2]
On my Arduino uno just with a new lcd shield from amazon like in your picture (black pcb and markings)
Select and Down buttons didn't work so i went into
Documents\Arduino\libraries\ErriezLCDKeypadShield-master\src\ErriezLCDKeypadShield.cpp

and changed:
    if (analogKey < 50) {
        key = ButtonRight;
    } else if (analogKey < 200) {
        key = ButtonUp;
    } else if (analogKey < 3**50**) {
        key = ButtonDown;
    } else if (analogKey < 500) {
        key = ButtonLeft;
    } else if (analogKey < 7**50**) {
        key = ButtonSelect;
    } else {
        key = ButtonNone;
    }

Reupload made it work on my uno so maybe you should include it somewhere

**Comment by Erriez** [comment]
Thanks for your comment. I can imagine that this works for you, because several companies manufactures the same board with different components/quality. I've updated the README.md to suggest users to experiment with the analog key values as you suggested.
